### ISSUE TITLE
Error opening config

### ISSUE THREAD

**Issue by nstuck** [Klixxx/AdiBags-Classic#1]
I'm getting an error when attempting to open the config:

Error in AdiBags: Interface\AddOns\AdiBags\config\Options-Options.lua:663: attempt to call method 'SetDefaultSize' (a nil value) --details: [Error 00000226F7830030]

**Comment by Klixxx** [comment]
Cant reproduce it, no errors when opening the config.

**Comment by dwfmagik** [comment]
I get an error opening config too.

Says cannot find aceaddon 'adibags'.

**Comment by nstuck** [comment]
Weird. Without changing anything at all. It works today. Didn't work yesterday, works today. Idk.

**Comment by Klixxx** [comment]
Im glad it works, as said before i cant reproduce this, everything works flawless
