### ISSUE TITLE
Please push to curse client? I must install from there.

### ISSUE THREAD

**Issue by strickland** [Klixxx/AdiBags-Classic#2]
Simple reason, china restriction on some sites, can't download some other sites, but curse client application can install easily, please? thanks

Make sure it's under classic for curse, cause it already exist under retail, but in classic when I search "New addon > Adibags" Only one shows is adibags elvui, which doesn't work, it requires elv ui..

**Comment by Klixxx** [comment]
Actually the one for ElvUI called “ElvUI AdiBags”, works without elvui lol, but only the classic version does that :)

So you can easily download that!
Thanks!
